import { PT_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";

import "./globals.css";

const nunito = PT_Sans({
  subsets: ["latin"],
  weight:["400", "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={nunito.className}>
          <div className="h-screen w-screen overflow-x-hidden">
            {/* <Header /> */}
            <div>
              <Provider>
              {children}
              </Provider>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
